baseURL = "//anglodiseno.github.io/testhugo/"
languageCode = "es-es"
title = "Test Hugo Site"
theme = "tale"


[menu]
  [[menu.main]]
    identifier = "contacto"
    name = "Contacto"
    title = "Contacto"
    url = "/contacto/"
    weight = 0
  [[menu.main]]
    identifier = "post"
    name = "Post"
    title = "Post"
    url = "/post/"
    weight = 0